---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=rideshare.conf.j2 dest=/etc/init/rideshare.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=rideshare state=restarted
