---

- name: Get DB Password
  include_vars: secrets.yml

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - postgresql-client
    - libpq-dev
    - python-pip
    - python-psycopg2
    - git

- name: Install UbuntuGis PPA
  apt_repository: repo="ppa:ubuntugis/ppa"
  sudo: yes

- name: Install PostGis
  apt: name=postgis state=present update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install PostGis Extension
  postgresql_ext: name=postgis db=rideshare login_host=rideshare.cpklkuhcfy5d.us-west-2.rds.amazonaws.com port=5432 login_user=rideshare login_password={{ db_password }}
  sudo: yes
# make the connection to the RDS and then run psql command to instantiate a spatialref table
# sudo -u postgres psql --host=rideshare.cpklkuhcfy5d.us-west-2.rds.amazonaws.com --port=5432 --username=rideshare --password --dbname=rideshare
# CREATE EXTENSION postgis;

- name: Clone Django Repository
  git: repo=https://github.com/RideQuest/rideshare-backend.git dest={{ django_home }} force=yes version=dev

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ django_home }}/requirements.txt"

- name: Get DB Hostvars
  set_fact:
    db_host: "{{ hostvars[groups[rds_db_instance][0]] }}"


- name: Set DB URL
  set_fact: 
    db_url: "{{ db_host.ec2_engine }}://{{ db_host.ec2_master_username }}:{{ db_password }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"

- name: Run Migrations
  environment:
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}/rideshare/"
    settings: rideshare.production
    command: migrate

# - name: Collect Static Files
#   environment:
#     DATABASE_URL: "{{ db_url }}"
#   django_manage:
#     app_path: "{{ django_home }}"
#     settings: mysite.production
#     command: collectstatic
